#!/bin/bash
Orignal_sequence=$1
Session_id=$2
reverse_complement=$(echo $Orignal_sequence| grep '^[ATCG]' | rev | tr ATCG TAGC)
grep -v -l "$Orignal_sequence\|$reverse_complement" Database/dir/* > tmp/"$Session_id".txt
##ANNOTATING THE LIST WITH NCBI METADATA
grep -oP 'GCA_[0-9]+' tmp/"$Session_id".txt | grep -f - Database/biosample_summary.txt | awk '{print $1,$2,$3,$4,$5,$6,$7,$8}' OFS='\t' FS='\t' > tmp/"$Session_id".annotated.txt